env: "local"  # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8123"
  timeout: 4s # время на чтение запроса и отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом -время пока мы ждем повторный запрос от клиента, чтобы не открывать несколько соединений на каждый запрос
  